services:
  - type: web
    name: fitid
    env: docker
    dockerfilePath: Dockerfile
    autoDeploy: true
    plan: starter
    envVars:
      - key: NEXTAUTH_URL
        value: "https://fit-id-uzzj.onrender.com"
      - key: NEXTAUTH_SECRET
        secure: true
      - key: GOOGLE_CLIENT_ID
        secure: true
      - key: GOOGLE_CLIENT_SECRET
        secure: true
      - key: ALLOWED_ORIGINS
        value: "https://fit-id-uzzj.onrender.com"
      - key: NEXT_PUBLIC_API_BASE
        value: "/api/v1"
      - key: JWT_SECRET
        secure: true
      - key: DATABASE_URL
        secure: true
      - key: FITID_PUBLIC_URL
        value: "https://fit-id-uzzj.onrender.com"
      - key: OAUTH_DEMO_CLIENT_ID
        secure: true
      - key: OAUTH_DEMO_CLIENT_SECRET
        secure: true
      - key: OAUTH_DEMO_REDIRECT_URIS
        value: "https://fit-id-uzzj.onrender.com/partner/demo/callback,https://fit-id-uzzj.onrender.com/callback"
